version: "3.8"

services:
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080
  mysql:
    container_name: mysql
    image: mysql
    ports:
    - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mntVolumeMYSQL:/var/lib/mysql
  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui
    ports:
      - 8181:8080
    environment:
      SWAGGER_JSON: /mnt/swagger.json
    volumes:
      - ./:/mnt
      

