CREATE DATABASE Laundry;

USE Laundry;

DROP TABLE IF EXISTS User;
CREATE TABLE User(
ID INT AUTO_INCREMENT,
Kode VARCHAR(255) UNIQUE DEFAULT NULL,
Nama VARCHAR(150) DEFAULT NULL,
Username VARCHAR(100) DEFAULT NULL,
Password VARCHAR(255) DEFAULT NULL,
Telepon VARCHAR(20) DEFAULT NULL,
PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS Unit;
CREATE TABLE Unit(
ID INT AUTO_INCREMENT,
Nama VARCHAR(50) NOT NULL UNIQUE,
PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS Layanan;
CREATE TABLE Layanan(
ID INT AUTO_INCREMENT,
Kode VARCHAR(255) UNIQUE DEFAULT NULL,
Nama VARCHAR(255) NOT NULL,
Harga DOUBLE NOT NULL,
UnitID INT NOT NULL,
UserID INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (UnitID) REFERENCES Unit(ID),
FOREIGN KEY (UserID) REFERENCES User(ID)
);

INSERT INTO Unit (Nama) VALUES ('kg');
INSERT INTO Unit (Nama) VALUES ('pcs');
INSERT INTO Unit (Nama) VALUES ('cm');
INSERT INTO Unit (Nama) VALUES ('m2'); 